version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/nodejs-template-master"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
